name: funagig-backend
services:
- name: api
  source_dir: /
  github:
    repo: Icradle-Innovations-Ltd/funagig1.5
    branch: master
  environment_slug: php
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: DB_HOST
    value: your-database-host.ondigitalocean.com
  - key: DB_PORT
    value: "25060"
  - key: DB_USER
    value: your-database-user
  - key: DB_PASS
    value: your-database-password
  - key: DB_NAME
    value: funagig
  - key: DB_SSL
    value: "false"
  - key: PRODUCTION_MODE
    value: "true"
  - key: DEBUG_MODE
    value: "false"
  - key: APP_URL
    value: ${_self.PUBLIC_URL}
  - key: HTTPS_REQUIRED
    value: "true"